In [33]:
import pandas as pd

df = pd.read_json('../data/olx_remote_work.json')
df

,id,text
0,http://www.olx.pl/oferta/praca/praca-zdalna-40...,"Nie, to nie pomyłka! Nie musisz dalej szukać, ..."
1,http://www.olx.pl/oferta/praca/praca-w-domu-dl...,W związku z prężnie rozwijającym się projektem...
2,http://www.olx.pl/oferta/praca/ankieter-zdalny...,Poszukujemy osoby do pracy zdalnej na stanowis...
3,http://www.olx.pl/oferta/praca/praca-handlowie...,Wynagrodzenie: 5-7 tys. zł.Umowa o pracęGodz. ...
4,http://www.olx.pl/oferta/praca/prowadzacy-kolk...,Jesteś studentem kierunków informatycznych lub...
...,...,...
1344,http://www.olx.pl/oferta/praca/tworzenie-grafi...,OGŁOSZENIE JEST NADAL AKTUALNE - NATOMIAST LIC...
1345,http://www.olx.pl/oferta/praca/tworzenie-grafi...,OGŁOSZENIE JEST NADAL AKTUALNE - NATOMIAST LIC...
1346,http://www.olx.pl/oferta/praca/latwa-dodatkowa...,"Szukamy osób do prostej pracy zdalnej, wykonyw..."
1347,http://www.olx.pl/oferta/praca/doradca-ubezpie...,Zadania na tym stanowisku:Nawiązywanie relacji...
1348,http://www.olx.pl/oferta/praca/prosta-praca-do...,Poszukujemy osób zainteresowanych prostą pracą...

In [34]:
df['text'] = df['text'].apply(lambda x: x.lower() if x is not None else '')

In [43]:
df.drop(['id'], axis=1, inplace=True)
df

                                                   text
0     nie, to nie pomyłka! nie musisz dalej szukać, ...
1     w związku z prężnie rozwijającym się projektem...
2     poszukujemy osoby do pracy zdalnej na stanowis...
3     wynagrodzenie: 5-7 tys. zł.umowa o pracęgodz. ...
4     jesteś studentem kierunków informatycznych lub...
...                                                 ...
1344  ogłoszenie jest nadal aktualne - natomiast lic...
1345  ogłoszenie jest nadal aktualne - natomiast lic...
1346  szukamy osób do prostej pracy zdalnej, wykonyw...
1347  zadania na tym stanowisku:nawiązywanie relacji...
1348  poszukujemy osób zainteresowanych prostą pracą...

[1349 rows x 1 columns]

In [44]:
vocab = []
with open('../data/suspicious_phrases.txt') as f:
    for line in f.readlines():
        vocab.append(line.strip())

vocab = pd.DataFrame(vocab, columns=['text'])
vocab

                               text
0                    sprzedam konto
1                       kupię konto
2        zapłacę za założenie konta
3       konto bankowe bez komornika
4          udostępnię konto bankowe
5              czyste konto bankowe
6          bezpieczne konto bankowe
7                     przelewy za %
8         procent od kwoty przelewu
9                    konto na słupa
10                             słup
11                tester bankowości
12                mam konto bankowe
13            konto bankowe od ręki
14                  przyjąć przelew
15   nawiążę długotrwałą współpracę
16        przelew na wskazane konto
17                 nie na moje dane
18  konta bankowe w różnych bankach
19                         prowizja
20           otworzyć konto bankowe
21               zajęcie komornicze
22         oferta mocno ograniczona
23             zakładane w oddziale
24                      brak blokad
25                     brak limitów
26                dokumenty z banku
27                    umowa bankowa
28                        karta sim
29                      skan dowodu
30                 długa współpraca
31                 stała współpraca
32              zbudowanie zaufania
33            gwarancja zadowolenia
34                     czyjeś konto
35              do legalnych rzeczy
36                          legalne
37         tylko poważne propozycje

In [45]:
df_with_phrases = pd.concat([df, vocab])
df_with_phrases

                                                 text
0   nie, to nie pomyłka! nie musisz dalej szukać, ...
1   w związku z prężnie rozwijającym się projektem...
2   poszukujemy osoby do pracy zdalnej na stanowis...
3   wynagrodzenie: 5-7 tys. zł.umowa o pracęgodz. ...
4   jesteś studentem kierunków informatycznych lub...
..                                                ...
33                              gwarancja zadowolenia
34                                       czyjeś konto
35                                do legalnych rzeczy
36                                            legalne
37                           tylko poważne propozycje

[1387 rows x 1 columns]

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(ngram_range=(1,5), min_df=10)
tfidf_data = tfidf.fit_transform(df_with_phrases['text'])
tfidf.get_feature_names_out()

array(['00', '00 15', '00 15 00', ...,
       'żywo klientemnie wymagamy dzwonienia',
       'żywo klientemnie wymagamy dzwonienia po', 'żądania'], dtype=object)

In [48]:
tfidf_matrix = pd.DataFrame(tfidf_data.todense(), columns = tfidf.get_feature_names_out()).astype('float32')
tfidf_matrix

,00,00 15,00 15 00,00 16,00 16 00,00 17,00 17 00,00 20,00 20 00,00 21,...,żywo,żywo klientem,żywo klientem nie,żywo klientem nie wymagamy,żywo klientem nie wymagamy dzwonienia,żywo klientemnie,żywo klientemnie wymagamy,żywo klientemnie wymagamy dzwonienia,żywo klientemnie wymagamy dzwonienia po,żądania
0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.037812,0.0,0.0,0.06728,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1383,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1384,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1385,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1386,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
df_with_phrases.shape

(1387, 1)

In [51]:
from nltk import ngrams
import re

def get_ngrams(offer):
    offer_ngrams_list = []
    offer_clean = re.sub('[\W]+', ' ', offer)
    offer_list = offer_clean.split()
    for i in range(2,5):
        offer_ngrams = ngrams(offer_list, i)
        for gram in offer_ngrams:
            offer_ngrams_list.append(gram)
    return offer_ngrams_list

df_with_phrases['ngrams'] = df_with_phrases['text'].apply(get_ngrams)

In [52]:
ngram_duplicates = pd.Series()
for ngrams in df_with_phrases['ngrams']:
    g = pd.Series(ngrams).value_counts()
    ngram_duplicates = pd.concat([ngram_duplicates,g[g>1]])

In [53]:
data = {'keys' : list(ngram_duplicates.index),
        'values' : ngram_duplicates.values}

ngram_duplicates = pd.DataFrame(data=data)
ngram_duplicates

                            keys  values
0                (nie, wymagamy)       4
1                (nie, działamy)       2
2                (nie, wymagamy)       2
3      (wymagamy, doświadczenia)       2
4           (branie, udziału, w)       2
...                          ...     ...
16379           (prostej, pracy)       2
16380       (do, prostej, pracy)       2
16381               (relacji, z)       2
16382             (w, sprzedaży)       2
16383              (praca, jest)       2

[16384 rows x 2 columns]

In [12]:
!python -m spacy download pl_core_news_lg

^C

In [54]:
import spacy

nlp_pl = spacy.load("pl_core_news_lg")
stopwords = nlp_pl.Defaults.stop_words

In [55]:
stopwords

{'a',
 'aby',
 'ach',
 'acz',
 'aczkolwiek',
 'aj',
 'albo',
 'ale',
 'alez',
 'ależ',
 'ani',
 'az',
 'aż',
 'bardziej',
 'bardzo',
 'beda',
 'bede',
 'bedzie',
 'bez',
 'bo',
 'bowiem',
 'by',
 'byc',
 'byl',
 'byla',
 'byli',
 'bylo',
 'byly',
 'bym',
 'bynajmniej',
 'być',
 'był',
 'była',
 'było',
 'były',
 'będzie',
 'będą',
 'będę',
 'cala',
 'cali',
 'caly',
 'cała',
 'cały',
 'chce',
 'choć',
 'ci',
 'cie',
 'ciebie',
 'cię',
 'co',
 'cokolwiek',
 'coraz',
 'cos',
 'coś',
 'czasami',
 'czasem',
 'czemu',
 'czy',
 'czyli',
 'często',
 'daleko',
 'dla',
 'dlaczego',
 'dlatego',
 'do',
 'dobrze',
 'dokad',
 'dokąd',
 'dosc',
 'dość',
 'duzo',
 'dużo',
 'dwa',
 'dwaj',
 'dwie',
 'dwoje',
 'dzis',
 'dzisiaj',
 'dziś',
 'gdy',
 'gdyby',
 'gdyz',
 'gdyż',
 'gdzie',
 'gdziekolwiek',
 'gdzies',
 'gdzieś',
 'go',
 'godz',
 'i',
 'ich',
 'ile',
 'im',
 'inna',
 'inne',
 'inny',
 'innych',
 'iv',
 'ix',
 'iz',
 'iż',
 'ja',
 'jak',
 'jakas',
 'jakaś',
 'jakby',
 'jaki',
 'jakichs',
 'jakichś',
 'jakie',
 'jakis',
 'jakiz',
 'jakiś',
 'jakiż',
 'jakkolwiek',
 'jako',
 'jakos',
 'jakoś',
 'je',
 'jeden',
 'jedna',
 'jednak',
 'jednakze',
 'jednakże',
 'jedno',
 'jednym',
 'jedynie',
 'jego',
 'jej',
 'jemu',
 'jesli',
 'jest',
 'jestem',
 'jeszcze',
 'jezeli',
 'jeśli',
 'jeżeli',
 'juz',
 'już',
 'ją',
 'kazdy',
 'każdy',
 'kiedy',
 'kierunku',
 'kilka',
 'kilku',
 'kims',
 'kimś',
 'kto',
 'ktokolwiek',
 'ktora',
 'ktore',
 'ktorego',
 'ktorej',
 'ktory',
 'ktorych',
 'ktorym',
 'ktorzy',
 'ktos',
 'ktoś',
 'która',
 'które',
 'którego',
 'której',
 'który',
 'których',
 'którym',
 'którzy',
 'ku',
 'lecz',
 'lub',
 'ma',
 'mają',
 'mam',
 'mamy',
 'mało',
 'mi',
 'miał',
 'miedzy',
 'mimo',
 'między',
 'mna',
 'mnie',
 'mną',
 'moga',
 'mogą',
 'moi',
 'moim',
 'moj',
 'moja',
 'moje',
 'moze',
 'mozliwe',
 'mozna',
 'może',
 'możliwe',
 'można',
 'mu',
 'musi',
 'my',
 'mój',
 'na',
 'nad',
 'nam',
 'nami',
 'nas',
 'nasi',
 'nasz',
 'nasza',
 'nasze',
 'naszego',
 'naszych',
 'natomiast',
 'natychmiast',
 'nawet',
 'nia',
 'nic',
 'nich',
 'nie',
 'niech',
 'niego',
 'niej',
 'niemu',
 'nigdy',
 'nim',
 'nimi',
 'niz',
 'nią',
 'niż',
 'no',
 'o',
 'obok',
 'od',
 'ok',
 'około',
 'on',
 'ona',
 'one',
 'oni',
 'ono',
 'oraz',
 'oto',
 'owszem',
 'pan',
 'pana',
 'pani',
 'po',
 'pod',
 'podczas',
 'pomimo',
 'ponad',
 'poniewaz',
 'ponieważ',
 'powinien',
 'powinna',
 'powinni',
 'powinno',
 'poza',
 'prawie',
 'przeciez',
 'przecież',
 'przed',
 'przede',
 'przedtem',
 'przez',
 'przy',
 'raz',
 'razie',
 'roku',
 'rowniez',
 'również',
 'sam',
 'sama',
 'sie',
 'się',
 'skad',
 'skąd',
 'soba',
 'sobie',
 'sobą',
 'sposob',
 'sposób',
 'swoje',
 'są',
 'ta',
 'tak',
 'taka',
 'taki',
 'takich',
 'takie',
 'takze',
 'także',
 'tam',
 'te',
 'tego',
 'tej',
 'tel',
 'temu',
 'ten',
 'teraz',
 'też',
 'to',
 'toba',
 'tobie',
 'tobą',
 'totez',
 'toteż',
 'totobą',
 'trzeba',
 'tu',
 'tutaj',
 'twoi',
 'twoim',
 'twoj',
 'twoja',
 'twoje',
 'twym',
 'twój',
 'ty',
 'tych',
 'tylko',
 'tym',
 'tys',
 'tzw',
 'tę',
 'u',
 'vi',
 'vii',
 'viii',
 'w',
 'wam',
 'wami',
 'was',
 'wasi',
 'wasz',
 'wasza',
 'wasze',
 'we',
 'według',
 'wie',
 'wiele',
 'wielu',
 'więc',
 'więcej',
 'wlasnie',
 'wszyscy',
 'wszystkich',
 'wszystkie',
 'wszystkim',
 'wszystko',
 'wtedy',
 'wy',
 'właśnie',
 'wśród',
 'xi',
 'xii',
 'xiii',
 'xiv',
 'xv',
 'z',
 'za',
 'zaden',
 'zadna',
 'zadne',
 'zadnych',
 'zapewne',
 'zawsze',
 'zaś',
 'ze',
 'zeby',
 'znow',
 'znowu',
 'znów',
 'zostal',
 'został',
 'żaden',
 'żadna',
 'żadne',
 'żadnych',
 'że',
 'żeby'}

In [56]:
import numpy as np

ngram_duplicates['stopwords'] = ngram_duplicates['keys'].apply(lambda x : 1 if any([word in x for word in stopwords]) else 0)

In [84]:
ngram_duplicates = ngram_duplicates[(ngram_duplicates['stopwords']==0) & (ngram_duplicates['values']>1)].sort_values(by=['values'], ascending=False).drop_duplicates(subset=['keys'])
ngram_duplicates.to_csv('../data/potential_phrases.csv')